DROP SYNONYM CADSR_API.OBJECT_CART_SEQ
/

DROP SYNONYM CADSR_API.CART_OBJECT_SEQ
/

DROP SEQUENCE OBJECT_CART_SEQ
/

DROP SEQUENCE CART_OBJECT_SEQ
/


CREATE TABLE CART ( 
    ID NUMBER(11) NOT NULL, 
    USER_ID VARCHAR2(255) NOT NULL, 
    CREATION_DATE DATE NOT NULL, 
    LAST_WRITE_DATE DATE DEFAULT NULL, 
    NAME VARCHAR2(255) NOT NULL, 
    EXPIRATION_DATE DATE DEFAULT NULL, 
    LAST_READ_DATE DATE DEFAULT NULL
    )
/

ALTER TABLE CART ADD CONSTRAINT PK_CART PRIMARY KEY (ID) 
/

CREATE UNIQUE INDEX CART_INDEX ON CART (USER_ID, NAME)
/

CREATE SEQUENCE OBJECT_CART_SEQ
 START WITH     10000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
/

CREATE TABLE CART_OBJECT (
      ID NUMBER(11) NOT NULL,
      DATA CLOB NOT NULL,
      CART_ID NUMBER(11) NOT NULL,
      DATE_ADDED DATE NOT NULL,
      NATIVE_ID VARCHAR2(255) DEFAULT NULL,
      DISPLAY_TEXT VARCHAR2(255) DEFAULT NULL,
      TYPE VARCHAR2(255) NOT NULL,
      RELATED_ID NUMBER(11) DEFAULT NULL
)
/

CREATE SEQUENCE CART_OBJECT_SEQ
 START WITH     10000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
/


ALTER TABLE CART_OBJECT ADD CONSTRAINT PK_CART_OBJECT PRIMARY KEY (ID) 
/

CREATE INDEX CART_OBJECT_ID_INDEX ON CART_OBJECT (CART_ID)
/

CREATE INDEX CART_OBJECT_TYPE_INDEX ON CART_OBJECT (TYPE)
/

CREATE INDEX CART_OBJECT_NATIVE_ID_INDEX ON CART_OBJECT (NATIVE_ID)
/

CREATE SYNONYM CADSR_API.CART FOR SBREXT.CART
/

CREATE SYNONYM CADSR_API.CART_OBJECT FOR SBREXT.CART_OBJECT
/

GRANT SELECT, INSERT, UPDATE, DELETE ON SBREXT.CART TO CADSR_API;
/

GRANT SELECT, INSERT, UPDATE, DELETE ON SBREXT.CART_OBJECT TO CADSR_API;
/

CREATE SYNONYM CADSR_API.OBJECT_CART_SEQ FOR SBREXT.OBJECT_CART_SEQ
/

CREATE SYNONYM CADSR_API.CART_OBJECT_SEQ FOR SBREXT.CART_OBJECT_SEQ
/

GRANT SELECT ON SBREXT.CART_OBJECT_SEQ TO CADSR_API;
/

GRANT SELECT ON SBREXT.OBJECT_CART_SEQ TO CADSR_API;
/

CREATE OR REPLACE TRIGGER Object_Cart_Type
  BEFORE INSERT OR UPDATE ON CART
  FOR EACH ROW
  WHEN (new.name != 'formCart' or new.name != 'cdeCart')
BEGIN
  RAISE_APPLICATION_ERROR( -20001, 'Object Cart name can only be either formCart or cdeCart. Invalid name: ' || :new.name );
END;
/